name: bench-gitea-github-tuned
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build image (no cache)
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t bench-gitea .
