name: bench-gitea-depot-tuned
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: depot-ubuntu-24.04-4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: depot/build-push-action@v1
        with:
          project: m6xl170cwf
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          tags: bench-gitea
