name: bench-gitea-depot-tuned
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: depot-ubuntu-24.04-4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: bench-gitea
          cache-from: type=gha
          cache-to: type=gha,mode=max
