name: bench-gitea-namespace-cold
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: namespace-profile-asgar
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Force cold cache
        run: |
          docker system prune -af
          docker builder prune -af
      - name: Build image (no cache)
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t bench-gitea .
